Correct indentation issue with editor in GitHub
Indention issue is fixed online with the GitHub online editor

diff --git a/.github/workflows/02-basic-jmeter-execution-example.yml b/.github/workflows/02-basic-jmeter-execution-example.yml
--- a/.github/workflows/02-basic-jmeter-execution-example.yml
+++ b/.github/workflows/02-basic-jmeter-execution-example.yml
@@ -33,19 +33,21 @@ jobs:
             exit 1
           fi
 
+#         ~/jmeter/bin/jmeter -n -t test-plan/test-plan-jmeter-website.jmx -l results/results.csv -j results/jmeter.log
+#         ~/jmeter/bin/jmeter -n -t test-plan/test-plan-jmeter-website.jmx -l results/results.csv -j results/jmeter.log || (echo "JMeter execution failed!" && cat results/jmeter.log && exit 1)
+
+
       # Step 4: Run JMeter test plan
       - name: Run JMeter test plan
         run: |
           mkdir -p results test-results
-#         ~/jmeter/bin/jmeter -n -t test-plan/test-plan-jmeter-website.jmx -l results/results.csv -j results/jmeter.log
-#          ~/jmeter/bin/jmeter -n -t test-plan/test-plan-jmeter-website.jmx -l results/results.csv -j results/jmeter.log || (echo "JMeter execution failed!" && cat results/jmeter.log && exit 1)
           ~/jmeter/bin/jmeter \
           -n \
           -t test-plan/test-plan-jmeter-website.jmx \
           -l results/results.csv \
           -j results/jmeter.log || ( \
-              echo "JMeter execution failed!" && \
-              cat results/jmeter.log && \
+          echo "JMeter execution failed!" && \
+          cat results/jmeter.log && \
           exit 1 \
           )
 
