Update with checkout version, format JMX execution statement, add echo statement for debugging

diff --git a/.github/workflows/06-data-driven-test-csv-example.yml b/.github/workflows/06-data-driven-test-csv-example.yml
--- a/.github/workflows/06-data-driven-test-csv-example.yml
+++ b/.github/workflows/06-data-driven-test-csv-example.yml
@@ -1,4 +1,4 @@
-name: Run JMeter Tests with CSV test data
+name: 06-Run JMeter Tests with CSV test data
 
 on:
   workflow_dispatch: # Allow manual trigger of this workflow
@@ -17,7 +17,7 @@ jobs:
     steps:
       # Step 1: Checkout the repository
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       # Step 2: Install JDK and required tools
       - name: Install JDK and wget
@@ -46,14 +46,24 @@ jobs:
       - name: Run JMeter test plan and generate HTML reports
         run: |
           mkdir -p ${{ env.TEST_REPORT_FOLDER }}
-          $HOME/jmeter/bin/jmeter -n -t ${{ env.TEST_PLAN_PATH }} -l ${{ env.TEST_REPORT_FOLDER }}/results.csv -j ${{ env.TEST_REPORT_FOLDER }}/jmeter.log -e -f -o ${{ env.TEST_REPORT_FOLDER }}/reports
-
+          $HOME/jmeter/bin/jmeter \
+          -n \
+          -t ${{ env.TEST_PLAN_PATH }} \
+          -l ${{ env.TEST_REPORT_FOLDER }}/results.csv \
+          -j ${{ env.TEST_REPORT_FOLDER }}/jmeter.log \
+          -e -f \
+          -o ${{ env.TEST_REPORT_FOLDER }}/reports || ( \
+          echo "JMeter execution failed! Check logs." && \
+          cat ${{ env.TEST_REPORT_FOLDER }}/jmeter.log && \
+          exit 1 \
+          )
 
       # Step 6: Move XML test result file to results folder (if exists)
-      - name: Move test-result.xml
+      - name: Move test-result.xml if exists
         run: |
           if [ -f "$GITHUB_WORKSPACE/test-result.xml" ]; then
             mv "$GITHUB_WORKSPACE/test-result.xml" ${{ env.TEST_REPORT_FOLDER }}/test-result.xml
+            echo "test-result.xml moved successfully."
           else
             echo "Warning: test-result.xml not found!"
           fi
